//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismMembership.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string FID { get; set; }
        public string PID { get; set; }
        public double Sequencer { get; set; }
        public string MT { get; set; }
        public string MT2 { get; set; }
        public string Salutation { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Surname1 { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public Nullable<System.DateTime> Renewal_date { get; set; }
        public string Lapsed_date { get; set; }
        public bool InYear { get; set; }
        public string Profession { get; set; }
        public string Spare { get; set; }
        public string X { get; set; }
    }
}
