//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismMembership.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public string FID { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> Renewal_Date { get; set; }
        public string House { get; set; }
        public string Road { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Post_Code { get; set; }
        public string Phone_No { get; set; }
        public string MTmain { get; set; }
        public string Social_Life { get; set; }
        public string e_mail { get; set; }
    }
}
